export const GET_STORAGE_DATA = 'GET_STORAGE_DATA';
export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';

export const CREATE_FOLDER = 'CREATE_FOLDER';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAILURE = 'CREATE_FOLDER_FAILURE';

export const UPLOUD_FILE = 'UPLOUD_FILE';
export const UPLOUD_FILE_SUCCESS = 'UPLOUD_FILE_SUCCESS';
export const UPLOUD_FILE_FAILURE = 'UPLOUD_FILE_FAILURE';

export const SET_PARENTID = 'SET_PARENTID';
