export const GET_STORAGE_DATA = 'GET_STORAGE_DATA';
export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';

export const CREATE_FOLDER = 'CREATE_FOLDER';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAILURE = 'CREATE_FOLDER_FAILURE';
